@startuml
'https://plantuml.com/class-diagram

abstract class Operation {
    *dateOperation
    *montantOperation
    +Operation(Date date, int montantOperation
    +abstract getType(): String
}

class Credit extends Operation {
    +getType(): String
 }
class Debit extends Operation {
    +getType(): String
}



@enduml