@startuml
'https://plantuml.com/class-diagram

abstract class Personne extends Adresse {
    +nom
    +prenom
    +numeroDeSecu
}

class Adresse {
    +numeroDeRue
    +rue
    +codePostal
    +ville
}

abstract class Employe extends Personne {
    +matriculeEmploye
}

class Cadre extends Employe{

}

class Technicien extends Employe{

}

class Commercial extends Employe{

}

class CoordonneeContactPerso extends Personne{
    +numeroTel
    +mail
}

class CoordonneeContactPro extends CoordonneeContactPerso {
    +service
    +adresseEntreprise
}

interface CaclulSalaire {

}

@enduml